server {
 listen 80; 
 server_name site-1.com;

 root /var/www/site-1.com;
 index index.html;

 error_page 404 /404.html;

access_log /var/log/nginx/site1_access.log;
error_log /var/log/nginx/site1_error.log;


 location = /404.html {
     root /var/www/site-1.com;
 }
 }
