



server{
	listen 443 ssl;
	server_name site-2.com;
	
	ssl_certificate /etc/nginx/ssl/certificate.crt;
	ssl_certificate_key /etc/nginx/ssl/private.key;

	location / {
	root /var/www/site-2.com;
	index index.html;
	}

	# error_page 
       error_page 404 /404.html;
       location = /404.html {
	root /var/www/site-2.com;
       }       
}


